modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPLv3"
[[mods]]
modId="minechess"
version="1.0"
displayName="MineChess"
credits="Sebastian Lague (https://github.com/SebLague)"
authors="Flash (https://github.com/FlashHUN)"
description='''
Chess in Minecraft!
'''
[[dependencies.minechess]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.minechess]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
